version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: superjson
    versions:
    - 1.5.0
    - 1.5.2
    - 1.6.1
    - 1.6.2
    - 1.7.2
    - 1.7.3
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: commander
    versions:
    - 7.1.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: ts-loader
    versions:
    - 8.0.15
