name: CI

on: [push]

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/yarn
          key: ${{ matrix.os }}-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ matrix.os }}-
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Building packages
        run: yarn build
      - name: Testing @fleur/fleur
        run: |
          cd packages/fleur
          yarn test --coverage --verbose
      - name: Testing @fleur/di
        run: |
          cd packages/di
          yarn test --coverage --verbose
      - name: Testing @fleur/react
        run: |
          cd packages/react
          yarn test --coverage --verbose
      - name: Testing @fleur/testing
        run: |
          cd packages/testing
          yarn test --coverage --verbose
      - name: Testing @fleur/create-next-app
        run: |
          cd packages/create-next-app
          node ./bin/index test-app
          cd test-app
          yarn install
          yarn run build
      - name: Testing @fleur/next
        run: |
          cd packages/next
      - name: Benchmarking (Performance)
        run: |
          cd packages/fleur-benchmarks
          yarn test
      - name: Benchmarking (Bundle size)
        run: |
          cd packages/fleur-benchmarks
          yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./
